# (c) https://github.com/MontiCore/monticore
name: Publish a Snapshot


on:
  workflow_run:
    workflows: [ gradle mc ]
    branches: [ dev, github-actions ]
    types:
      - completed

permissions:
  contents: read
  packages: write

env:
  GRADLE_VERSION: 7.4 # Gradle version used
  GRADLE_CLI_OPTS: "-Pci" # CLI option passed to Gradle

jobs:
  # Deploy the snapshot-publications to the snapshot repository (both nexus and GitHub Packages)
  deploy-snapshot:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only run if tests were successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Deploy the snapshot
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{env.GRADLE_VERSION}}
          arguments: deployMC ${{env.GRADLE_CLI_OPTS}} -PmavenPassword=${{env.MAVEN_PASSWORD}} -PmavenUser=${{env.MAVEN_USER}} -PgenEMF=true -PgenTR=true -PgenTagging=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USER: ${{ secrets.SE_NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.SE_NEXUS_PASSWORD }}

# TODO: Trigger Downstream Projects (both on GitHub and GitLab)