# .github/workflows/gradle_mc.yml
name: Build & Test Gradle projects


on:
  release:
    types:
      - created

env:
  GRADLE_VERSION: 7.4 # Gradle version used
  GRADLE_CLI_OPTS: "-Pci --scan" # CLI option passed to Gradle

  # Deploy the release  to the snapshot nexus
  deploy-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Test 01.experiments
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{env.GRADLE_VERSION}}
          # pass the tag as the version property
          arguments: build publishMC ${{env.GRADLE_CLI_OPTS}} -PgenEMF=true -PgenTR=true -PgenTagging=true -Pversion="$MC_RELEASE_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MC_RELEASE_VERSION: ${{ github.ref_name }}

