name: Build Gradle project

on:
  push:

# Cache per commit
#env:
#  GRADLE_BUILD_ACTION_CACHE_KEY_JOB: "test-cache-${{ github.head_ref }}.${{ github.sha }}"


env:
    GRADLE_VERSION: 7.4
    GRADLE_OPTS: "-Pci"

jobs:

  build-generator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Build the monticore-generator
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: ${{env.GRADLE_VERSION}}
       arguments: build ${{env.GRADLE_OPTS}} -p monticore-generator --info

  build-mc:
    runs-on: ubuntu-latest
    needs: build-generator
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Build monticore (buildMC)
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: ${{env.GRADLE_VERSION}}
       arguments: buildMC ${{env.GRADLE_OPTS}} -PgenTR=true -PgenEMF=true -PgenTagging=true --scan

  test-01-experiments:
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version:  ${{env.GRADLE_VERSION}}
       cache-read-only: true
       arguments: build test ${{env.GRADLE_OPTS}} -p monticore-test/01.experiments -PgenEMF=true --scan
  test-02-experiments:
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test ${{env.GRADLE_OPTS}} -p monticore-test/02.experiments -PgenEMF=false --scan # todo reenable emf

  test-it:
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test integration tests
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test ${{env.GRADLE_OPTS}} -p monticore-test/it --build-cache

  test-it-emf:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test IT EMF
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/it -Pci -PbuildProfile=emf -PgenEMF=true --build-cache


  test-grammar-it:
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test grammar IT
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/monticore-grammar-it -Pci --build-cache

  test-montitrans:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/montitrans -PgenTR=true -Pci --build-cache