name: Build Gradle project

on:
  push:

# try without the gradle cache
#env:
#  GRADLE_BUILD_ACTION_CACHE_KEY_JOB: "test-cache-${{ github.head_ref }}.${{ github.sha }}"

jobs:
  build-mc-gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Build the monticore-generator
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       arguments: build -p monticore-generator -Pci --info  --build-cache
    - name: Build monticore (buildMC)
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       arguments: buildMC -Pci -PgenTR=false -PgenEMF=false -PgenTagging=false --info --build-cache # TODO: reenable emf/tr/tagging

  test-01-experiments:
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/01.experiments -PgenEMF=false -Pci --info --build-cache # todo reenable emf
 #  --build-cache
  test-02-experiments:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    #- name: Checkout project sources
    #  uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/02.experiments -PgenEMF=true -Pci

  test-it:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/gradle-build-action@v2
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/it -Pci

  test-it-emf:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/gradle-build-action@v2
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/it -Pci -PbuildProfile=emf -PgenEMF=true


  test-grammar-it:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/gradle-build-action@v2
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/monticore-grammar-it -Pci

  test-montitrans:
    if: false
    runs-on: ubuntu-latest
    needs: build-mc-gradle
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Test using Gradle
      uses: gradle/gradle-build-action@v2
      with:
       gradle-version: 7.4
       cache-read-only: true
       arguments: build test -p monticore-test/montitrans -PgenTR=true -Pci