# (c) https://github.com/MontiCore/monticore
name: Trigger MontiVerse (downstream projects)

concurrency: # run this deploy workflow only once per "branch"
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [ Build & Test ]
    branches: [ dev, github-actions ]
    types:
      - completed

permissions:
  contents: read

jobs:
  # Run the MontiVerse pipeline (tests this change on a suite of projects)
  trigger-montiverse:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only run if tests were successful
    runs-on: ubuntu-latest
    steps:
      - name: Trigger MontiVerse
        uses: digital-blueprint/gitlab-pipeline-trigger-action@v1
        with:
          host: 'git.rwth-aachen.de'
          trigger_token: ${{ secrets.MONTIVERSE_TRIGGER_TOKEN }}
          access_token: ${{ secrets.MONTIVERSE_ACCESS_TOKEN }}  # Access is required to show the status
          id: '91803'  # montiverseci project id
          ref: 'main'
          variables: '{"MONTICORE_BRANCH":"${{env.GITHUB_REF}}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USER: ${{ secrets.SE_NEXUS_USER }}
          MAVEN_PASSWORD: ${{ secrets.SE_NEXUS_PASSWORD }}

        # TODO: Proper message in PRs?

# TODO: Trigger Downstream Projects (both on GitHub and GitLab)